### ISSUE TITLE
ShouldBeUnique Bug

### ISSUE THREAD

**Issue by DimaVIII** [mateusjunges/trackable-jobs-for-laravel#45] opened 2023-08-17 09:35 UTC
If a Job implements `ShouldBeUnique` a new `trackedJob` is created even Laravel discarded the "duplicated" Job from the Queue.

Further checks need to be in implemented in the `Trackable` trait constructor before creating the model.

Test Job:
 ```php
class DebugJob implements ShouldQueue, ShouldBeUnique
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;
    use Trackable;

    public function uniqueId(): string
    {
        return $this->trackable->id ?? $this->trackable->uuid;
    }


    public function handle()
    {
        sleep(30);
    }
}
```

Dispatch few times in 30 sec:
```php
    $someModel = SomeModel::first();
    DebugJob::dispatch($someModel);
```

**Comment by mateusjunges** [comment] 2024-01-30 17:10
Hey @DimaVIII 👋 sorry about the late reply here. I'm trying to come up with a fix for this. Could you take a look at my PR when you have the time?

**Comment by mateusjunges** [comment] 2024-11-18 14:49
This is not a bug. Please see the discussion on #47 for more details.

**Closed by mateusjunges** 2024-11-18 14:49 UTC
